services:
  postgres:
    extends:
      file: ../common-services.yml
      service: postgres-common
    ports:
      - "${DB__PORT}:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  migration:
    extends:
      file: ../common-services.yml
      service: migration-common
    environment:
      DB__HOST: postgres
      DB__PORT: 5432
      DB__USER: ${DB__USER}
      DB__PASSWORD: ${DB__PASSWORD}
      DB__NAME: ${DB__NAME}
    depends_on:
      postgres:
        condition: service_healthy

  social-network:
    extends:
      file: ../common-services.yml
      service: social-network-common
    environment:
      LEVEL: "INFO"
      SERVER__BIND_PORT: ${SERVER__BIND_PORT}
      SERVER__BIND_HOST: "0.0.0.0"
      SERVER__WORKERS: "1"
      DB__TYPENAME: "postgresql+asyncpg"
      DB__HOST: postgres
      DB__PORT: 5432
      DB__USER: ${DB__USER}
      DB__PASSWORD: ${DB__PASSWORD}
      DB__NAME: ${DB__NAME}
      DB__POOL_SIZE: "1"
      AUTH__SECRET: ${AUTH__SECRET}
      AUTH__ALGORITHM: "HS256"
      AUTH__TOKEN_TTL_SECONDS: "604800"
      SENTRY__DSN: ${SENTRY_DSN:-}
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

volumes:
  pg-data:
