services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB__USER} -d ${DB__NAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - sn-network

  migration:
    build:
      context: ../..
      dockerfile: devops/social_network/Dockerfile
    command: python -m alembic -c social_network/infrastructure/database/migrations/alembic.ini upgrade head
    environment:
      DB__HOST: postgres
      DB__PORT: 5432
      DB__USER: ${DB__USER}
      DB__PASSWORD: ${DB__PASSWORD}
      DB__NAME: ${DB__NAME}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sn-network

  bootstrap:
    extends:
      file: ../common-services.yml
      service: bootstrap-common
    environment:
      DB__HOST: postgres
      DB__PORT: 5432
      DB__USER: ${DB__USER}
      DB__PASSWORD: ${DB__PASSWORD}
      DB__NAME: ${DB__NAME}
      MY_PASSWORD: ${MY_PASSWORD}
      MY_UUID: ${MY_UUID}
      AUTH__SECRET: ${AUTH__SECRET}
      AUTH__ALGORITHM: "HS256"
      AUTH__TOKEN_TTL_SECONDS: "604800"
    depends_on:
      migration:
        condition: service_completed_successfully
    networks:
      - sn-network

  social-network:
    build:
      context: ../..
      dockerfile: devops/social_network/Dockerfile
    command: python -m social_network.main
    ports:
      - "${SERVER__BIND_PORT}:${SERVER__BIND_PORT}"
    environment:
      LEVEL: "INFO"
      SERVER__BIND_PORT: ${SERVER__BIND_PORT}
      SERVER__BIND_HOST: "0.0.0.0"
      SERVER__WORKERS: "1"
      DB__TYPENAME: "postgresql+asyncpg"
      DB__HOST: postgres
      DB__PORT: 5432
      DB__USER: ${DB__USER}
      DB__PASSWORD: ${DB__PASSWORD}
      DB__NAME: ${DB__NAME}
      DB__POOL_SIZE: "1"
      AUTH__SECRET: ${AUTH__SECRET}
      AUTH__ALGORITHM: "HS256"
      AUTH__TOKEN_TTL_SECONDS: "604800"
      SENTRY__DSN: ${SENTRY_DSN:-}
      REDIS__HOST: "redis"
      REDIS__PORT: ${REDIS__PORT}
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    networks:
      - sn-network

volumes:
  pg-data:

networks:
  sn-network:
    driver: bridge
