# run as: docker compose --env-file .env.local up --build

services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m alembic -c social_network/database/migrations/alembic.ini upgrade head
    environment:
      DB__HOST: ${DB__HOST}
      DB__USER: ${DB__USER}
      DB__PASSWORD: ${DB__PASSWORD}
      DB__NAME: ${DB__NAME}
    depends_on:
      postgres:
        condition: service_healthy

  social-network:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m social_network.main
    ports:
      - "8081:${SERVER__BIND_PORT}"
    environment:
      DB__HOST: ${DB__HOST}
      DB__USER: ${DB__USER}
      DB__PASSWORD: ${DB__PASSWORD}
      DB__NAME: ${DB__NAME}
      SERVER__BIND_PORT: ${SERVER__BIND_PORT}
      AUTH__SECRET: ${AUTH__SECRET}
      AUTH__ALGORITHM: ${AUTH__ALGORITHM}
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
