"""init

Revision ID: 0efe9dc70af6
Revises:
Create Date: 2025-07-04 13:45:47.598289

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0efe9dc70af6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("first_name", sa.VARCHAR(length=256), nullable=False),
        sa.Column("second_name", sa.VARCHAR(length=256), nullable=False),
        sa.Column("birthdate", sa.DateTime(timezone=True), nullable=False),
        sa.Column("biography", sa.TEXT(), nullable=False),
        sa.Column("city", sa.VARCHAR(length=256), nullable=False),
        sa.Column("password", sa.VARCHAR(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
