"""feed-indexes

Revision ID: 88cb3e9697cd
Revises: 09edd852217e
Create Date: 2025-10-01 14:48:16.899846

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "88cb3e9697cd"
down_revision: Union[str, None] = "09edd852217e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_friends_friend_id"), "friends", ["friend_id"], unique=False
    )
    op.create_index(op.f("ix_friends_user_id"), "friends", ["user_id"], unique=False)
    op.create_index(op.f("ix_posts_author_id"), "posts", ["author_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_posts_author_id"), table_name="posts")
    op.drop_index(op.f("ix_friends_user_id"), table_name="friends")
    op.drop_index(op.f("ix_friends_friend_id"), table_name="friends")
    # ### end Alembic commands ###
