"""chats-message-text

Revision ID: a901d0d1f709
Revises: 89456e22475c
Create Date: 2025-10-06 00:41:19.197004

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a901d0d1f709"
down_revision: Union[str, None] = "89456e22475c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_messages", sa.Column("text", sa.VARCHAR(length=256), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_messages", "text")
    # ### end Alembic commands ###
