"""chats-partition

Revision ID: e04f753fc730
Revises: 8927218df365
Create Date: 2025-10-06 22:55:33.182039

"""

import datetime
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e04f753fc730"
down_revision: Union[str, None] = "8927218df365"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"""
        CREATE TABLE IF NOT EXISTS chat_messages_{datetime.datetime.now().year} PARTITION OF chat_messages
        FOR VALUES FROM ('{datetime.datetime.now().year}-01-01') TO ('{datetime.datetime.now().year}-12-31');
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        f"""DELETE TABLE IF EXISTS chat_messages_{datetime.datetime.now().year}"""
    )
    # ### end Alembic commands ###
