"""gin-idx

Revision ID: 424d3bd19959
Revises: 0efe9dc70af6
Create Date: 2025-09-22 22:55:40.544957

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "424d3bd19959"
down_revision: Union[str, None] = "0efe9dc70af6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.create_index(
        "first_name_gin_idx",
        "users",
        ["first_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"first_name": "gin_trgm_ops"},
    )
    op.create_index(
        "second_name_gin_idx",
        "users",
        ["second_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"second_name": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "second_name_gin_idx",
        table_name="users",
        postgresql_using="gin",
        postgresql_ops={"second_name": "gin_trgm_ops"},
    )
    op.drop_index(
        "first_name_gin_idx",
        table_name="users",
        postgresql_using="gin",
        postgresql_ops={"first_name": "gin_trgm_ops"},
    )
    op.execute("DROP EXTENSION IF NOT EXISTS pg_trgm;")
    # ### end Alembic commands ###
