global:
  scrape_interval:      15s
  evaluation_interval:  15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: postgresql
    static_configs:
      - targets: ['postgresql-exporter-master:9187', 'postgresql-exporter-slave1:9187', 'postgresql-exporter-slave2:9187']
