services:
  timescaledb:
    extends:
      file: ../common-services.yml
      service: timescaledb-common
    volumes:
      - timescaledb-data-indexes:/var/lib/postgresql/data

  grafana:
    extends:
      file: ../common-services.yml
      service: grafana-common
    volumes:
      - grafana-storage-indexes:/var/lib/grafana
      - ../monitoring/grafana-provisioning/:/etc/grafana/provisioning

  postgres:
    extends:
      file: ../common-services.yml
      service: postgres-common
    ports:
      - "${DB__PORT}:5432"
    volumes:
      - pg-data-indexes:/var/lib/postgresql/data

  migration:
    extends:
      file: ../common-services.yml
      service: migration-common
    command: python -m alembic -c social_network/infrastructure/database/migrations/alembic.ini upgrade 0efe9dc70af6
    environment:
      DB__HOST: postgres
      DB__PORT: 5432
      DB__USER: ${DB__USER}
      DB__PASSWORD: ${DB__PASSWORD}
      DB__NAME: ${DB__NAME}
    depends_on:
      postgres:
        condition: service_healthy

  social-network:
    extends:
      file: ../common-services.yml
      service: social-network-common
    environment:
      LEVEL: "INFO"
      SERVER__BIND_PORT: ${SERVER__BIND_PORT}
      SERVER__BIND_HOST: "0.0.0.0"
      SERVER__WORKERS: "1"
      DB__TYPENAME: "postgresql+asyncpg"
      DB__HOST: postgres
      DB__PORT: 5432
      DB__USER: ${DB__USER}
      DB__PASSWORD: ${DB__PASSWORD}
      DB__NAME: ${DB__NAME}
      DB__POOL_SIZE: "1"
      AUTH__SECRET: ${AUTH__SECRET}
      AUTH__ALGORITHM: "HS256"
      AUTH__TOKEN_TTL_SECONDS: "604800"
      SENTRY__DSN: ${SENTRY_DSN:-}
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

volumes:
  timescaledb-data-indexes:
  grafana-storage-indexes:
  pg-data-indexes:
