x-environment: &default-environment
  DATABASE_URL: postgres://postgres:postgres@glitchtip-postgres:5432/postgres
  REDIS_URL: redis://glitchtip-redis:6379/0
  SECRET_KEY: change_me_to_something_random # best to run openssl rand -hex 32
  PORT: 8000 # If changing, change the web service port too
  EMAIL_URL: consolemail:// # Example smtp://email:password@smtp_url:port https://glitchtip.com/documentation/install#configuration
  GLITCHTIP_DOMAIN: https://glitchtip.example.com # Change this to your domain
  DEFAULT_FROM_EMAIL: email@example.com # Change this to your email
  CELERY_WORKER_AUTOSCALE: "1,3" # Scale between 1 and 3 to prevent excessive memory usage. Change it or remove to set it to the number of cpu cores.

x-depends_on: &default-depends_on
  - glitchtip-postgres
  - glitchtip-redis

services:
  glitchtip-postgres:
    image: postgres:17.5
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust" # Consider removing this and setting a password
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
  glitchtip-redis:
    image: valkey/valkey
    restart: unless-stopped
  glitchtip-web:
    image: glitchtip/glitchtip
    depends_on: *default-depends_on
    ports:
      - "8000:8000"
    environment: *default-environment
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads
  glitchtip-worker:
    image: glitchtip/glitchtip
    command: ./bin/run-celery-with-beat.sh
    depends_on: *default-depends_on
    environment: *default-environment
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads
  glitchtip-migrate:
    image: glitchtip/glitchtip
    depends_on: *default-depends_on
    command: ./bin/run-migrate.sh
    environment: *default-environment

volumes:
  pg-data:
  uploads:
